INSERT INTO COMPOSANTE (NOM_COMPOSANTE) VALUES ('Carte');
INSERT INTO COURS (INTITULE_COURS, DATE_COURS, ID_COMPOSANTE) VALUES ('Cours de langue étrangère', '2020-01-01', 1);
INSERT INTO COURS (INTITULE_COURS, DATE_COURS, ID_COMPOSANTE) VALUES ('Cours de philosophie', '2020-01-01', 2);
INSERT INTO COURS (INTITULE_COURS, DATE_COURS, ID_COMPOSANTE) VALUES ('Cours de langue morte', '2020-01-01', 3);
INSERT INTO COURS (INTITULE_COURS, DATE_COURS, ID_COMPOSANTE) VALUES ('Cours de vieille langue', '2020-01-01', 4);

INSERT INTO CRENEAU (DATE_CRENEAU, ID_COURS) VALUES ('2020-01-01', 1);
INSERT INTO CRENEAU (DATE_CRENEAU, ID_COURS) VALUES ('2020-01-01', 2);
INSERT INTO CRENEAU (DATE_CRENEAU, ID_COURS) VALUES ('2020-01-01', 3);
INSERT INTO CRENEAU (DATE_CRENEAU, ID_COURS) VALUES ('2020-01-01', 4);

INSERT INTO VACATAIRE (LOGIN, MOT_DE_PASSE, NOM_USUEL, PRENOM, MAIL) VALUES ('dupond_jean', 'mdp', 'DUPOND', 'Jean', 'jean.dupond@univ.fr');
INSERT INTO VACATAIRE (LOGIN, MOT_DE_PASSE, NOM_USUEL, PRENOM, MAIL) VALUES ('dupont_jeanne', 'mdp', 'DUPONT', 'Jeanne', 'jeanne.dupont@univ.fr');

