INSERT INTO COMPOSANTE (NOM_COMPOSANTE) VALUES ('Carte');

INSERT INTO COURS (INTITULE) VALUES ('Cours de langue étrangère');
INSERT INTO COURS (INTITULE) VALUES ('Cours de philosophie');
INSERT INTO COURS (INTITULE) VALUES ('Cours de langue morte');
INSERT INTO COURS (INTITULE) VALUES ('Cours de vieille langue');

INSERT INTO CRENEAU (DATE_HEURE, DUREE, TYPE, COURS_ID) VALUES ('2020-01-01', 120, 'TP', 1);
INSERT INTO CRENEAU (DATE_HEURE, DUREE, TYPE, COURS_ID) VALUES ('2020-01-01', 120, 'TP', 1);
INSERT INTO CRENEAU (DATE_HEURE, DUREE, TYPE, COURS_ID) VALUES ('2020-01-01', 120, 'TP', 1);
INSERT INTO CRENEAU (DATE_HEURE, DUREE, TYPE, COURS_ID) VALUES ('2020-01-01', 120, 'TP', 1);

INSERT INTO VACATAIRE (LOGIN, MOT_DE_PASSE, NOM_USUEL, PRENOM) VALUES ('dupond_jean', 'mdp', 'DUPOND', 'Jean');
INSERT INTO VACATAIRE (LOGIN, MOT_DE_PASSE, NOM_USUEL, PRENOM) VALUES ('dupont_jeanne', 'mdp', 'DUPONT', 'Jeanne');

